project_id = "kgtscjvgipowuvuindxt"

[functions.reset-garage-password]
verify_jwt = false

[functions.create-garage]
verify_jwt = false

[functions.track-analytics]
verify_jwt = false

[functions.update-garage-email]
verify_jwt = false